// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/liuyongchang/Documents/beifa/dumi2.0-demo/node_modules/.pnpm/dumi@2.1.14_u3samvbzvrksr3cjfq3oe55axi/node_modules/dumi/theme-default/slots/Sidebar/index.js';
